--- 
driver_config: 
  box: opscode-ubuntu-12.04
  box_url: "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box"
driver_plugin: vagrant
platforms: 
  - 
    attributes: 
      private_ips: 
        - "192.168.0.2"
      public_ips: 
        - "192.168.0.2"
    driver_config: 
      customize: 
        memory: 1024
      network: 
        - 
          - private_network
          - 
            ip: "192.168.0.2"
    name: mgm
    run_list: 
      - "recipe[kagent::install]"
      - "recipe[ndb::install]"
      - "recipe[ndb::mgmd]"
      - "recipe[ndb::mysqld]"
      - "recipe[ndb::memcached]"
  - 
    attributes: 
      private_ips: 
        - "192.168.0.3"
      public_ips: 
        - "192.168.0.3"
    driver_config: 
      customize: 
        memory: 2048
      network: 
        - 
          - private_network
          - 
            ip: "192.168.0.3"
    name: ndbd
    run_list: 
      - "recipe[kagent::install]"
      - "recipe[ndb::install]"
      - "recipe[ndb::ndbd]"
suites: 
  - 
    attributes: 
      mysql: 
        run_as_user: mysql
      ndb: 
        DataMemory: "111"
        dir: /tmp
        memcached: 
          private_ips: 
            - "192.168.0.2"
        mgmd: 
          private_ips: 
            - "192.168.0.2"
        mysql_port: 3399
        mysql_socket: /tmp/mysql-alt.sock
        mysqld: 
          private_ips: 
            - "192.168.0.2"
        ndbd: 
          private_ips: 
            - "192.168.0.3"
      vagrant: "true"
    name: default
    run_list: ~
