---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpuexecutioncap: 90
    cpus: 2
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.0
#  - name: ubuntu-15.04

- name: mgm
  run_list:
  - recipe[kagent::install]
  - recipe[ndb::install]
  - recipe[ndb::mgmd]
  - recipe[ndb::mysqld]
  - recipe[ndb::memcached]
  attributes:
    private_ips: ["192.168.0.2"]
    public_ips: ["192.168.0.2"]
  driver_config:
    customize:
      memory: 1024
    network:
      - ['private_network', {ip: '192.168.0.2'}]

- name: ndbd
  run_list:
  - recipe[kagent::install]
  - recipe[ndb::install]
  - recipe[ndb::ndbd]
  attributes:
    private_ips: ["192.168.0.3"]
    public_ips: ["192.168.0.3"]
  driver_config:
    customize:
      memory: 2048
    network:
      - ['private_network', {ip: '192.168.0.3'}]

suites:
  - name: default
    run_list:
    attributes:
         mysql:
            run_as_user: mysql
         ndb:
            dir: "/tmp"
            DataMemory: "111"
            mgmd:
               private_ips: ["192.168.0.2"]
            ndbd:
               private_ips: ["192.168.0.3"]
            mysqld:
               private_ips: ["192.168.0.2"]
            memcached:
               private_ips: ["192.168.0.2"]
            mysql_port: 3399
            mysql_socket: /tmp/mysql-alt.sock
         vagrant: "true"
